"""
Python script and SLURM job-script generators.
"""

from __future__ import annotations

from textwrap import dedent
from typing import Literal

SimMode = Literal["single_point", "optimization", "md"]


def generate_script(
    structure_filename: str,
    model: str,
    device: str,
    dtype: str,
    mode: SimMode,
    # optimisation parameters
    optimizer: str = "FIRE",
    fmax: float = 0.05,
    max_steps: int = 500,
    relax_cell: bool = False,
    pressure_gpa: float = 0.0,
    # MD parameters
    ensemble: str = "NVT-Langevin",
    temperature_k: float = 300.0,
    timestep_fs: float = 1.0,
    n_steps: int = 1000,
    friction: float = 0.01,
) -> str:
    """Generate a standalone, HPC-ready Python script for a MACE simulation.

    The generated script is self-contained, readable, and requires only
    ASE and MACE to be installed in the target environment.

    Parameters
    ----------
    structure_filename:
        Name of the input structure file (will be read with ``ase.io.read``).
    model:
        MACE model size (``'small'``/``'medium'``/``'large'``) or path to a
        custom ``.model`` file.
    device:
        Torch device string: ``'auto'``, ``'cpu'``, or ``'cuda'``.
    dtype:
        Floating-point precision: ``'float32'`` or ``'float64'``.
    mode:
        Simulation mode: ``'single_point'``, ``'optimization'``, or ``'md'``.
    optimizer, fmax, max_steps, relax_cell, pressure_gpa:
        Optimisation parameters (used when *mode* is ``'optimization'``).
    ensemble, temperature_k, timestep_fs, n_steps, friction:
        MD parameters (used when *mode* is ``'md'``).

    Returns
    -------
    str
        Complete, executable Python script as a string.
    """
    mode_title = mode.replace("_", " ").title()

    header = dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"
        MACE simulation script — generated by CMN-MACE Studio
        Mode     : {mode_title}
        Structure: {structure_filename}
        \"\"\"

        import torch
        import numpy as np
        from ase.io import read, write
        from mace.calculators import mace_mp

        # ── Device ─────────────────────────────────────────────────────────────────
        device = "{device}"  # 'auto', 'cuda', or 'cpu'
        if device == "auto":
            device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Using device: {{device}}")

        # ── Structure ───────────────────────────────────────────────────────────────
        atoms = read("{structure_filename}")
        print(f"Loaded  : {{atoms.get_chemical_formula()}} — {{len(atoms)}} atoms")

        # ── Calculator ──────────────────────────────────────────────────────────────
        calc = mace_mp(
            model="{model}",
            device=device,
            default_dtype="{dtype}",
        )
        atoms.calc = calc

        """)

    # ── Mode-specific body ──────────────────────────────────────────────────────
    if mode == "single_point":
        body = dedent("""\
            # ── Single Point ───────────────────────────────────────────────────────────
            energy = atoms.get_potential_energy()
            forces = atoms.get_forces()
            max_force = float(np.max(np.linalg.norm(forces, axis=1)))

            print(f"Energy  : {energy:.6f} eV")
            print(f"Max force: {max_force:.4f} eV/Å")

            np.savetxt("forces.txt", forces, header="fx fy fz  [eV/Å]")
            print("Wrote forces.txt")
            """)

    elif mode == "optimization":
        _opt_imports: dict[str, str] = {
            "FIRE": "from ase.optimize import FIRE",
            "BFGS": "from ase.optimize import BFGS",
            "LBFGS": "from ase.optimize import LBFGS",
        }
        opt_import = _opt_imports.get(optimizer, "from ase.optimize import FIRE")

        if relax_cell:
            pressure_ev = pressure_gpa * 6.2415091e-3
            cell_block = dedent(f"""\
                try:
                    from ase.filters import ExpCellFilter
                except ImportError:
                    from ase.constraints import ExpCellFilter
                # {pressure_gpa} GPa → eV/Å³
                system = ExpCellFilter(atoms, scalar_pressure={pressure_ev:.8f})
                """)
        else:
            cell_block = "system = atoms\n"

        body = (
            dedent(f"""\
                # ── Geometry Optimisation ──────────────────────────────────────────────────
                {opt_import}
                import csv

                """)
            + cell_block
            + dedent(f"""\

                history = []

                def record():
                    e = atoms.get_potential_energy()
                    f = atoms.get_forces()
                    history.append({{
                        "step": len(history),
                        "energy": e,
                        "max_force": float(np.max(np.linalg.norm(f, axis=1))),
                    }})

                opt = {optimizer}(system, logfile="opt.log", trajectory="opt.traj")
                record()        # initial state
                opt.attach(record)
                opt.run(fmax={fmax}, steps={max_steps})

                print(f"Final energy  : {{atoms.get_potential_energy():.6f}} eV")
                write("relaxed.vasp", atoms)

                with open("convergence.csv", "w", newline="") as fh:
                    writer = csv.DictWriter(fh, fieldnames=["step", "energy", "max_force"])
                    writer.writeheader()
                    writer.writerows(history)

                print("Wrote relaxed.vasp and convergence.csv")
                """)
        )

    elif mode == "md":
        if ensemble == "NVT-Langevin":
            dyn_block = dedent(f"""\
                from ase.md.langevin import Langevin
                from ase.units import fs as FS
                from ase.md.velocitydistribution import MaxwellBoltzmannDistribution

                MaxwellBoltzmannDistribution(atoms, temperature_K={temperature_k})

                dyn = Langevin(
                    atoms,
                    timestep={timestep_fs} * FS,
                    temperature_K={temperature_k},
                    friction={friction} / FS,
                    logfile="md.log",
                    trajectory="md.traj",
                )
                """)
        else:
            dyn_block = dedent(f"""\
                from ase.md.verlet import VelocityVerlet
                from ase.units import fs as FS
                from ase.md.velocitydistribution import MaxwellBoltzmannDistribution

                MaxwellBoltzmannDistribution(atoms, temperature_K={temperature_k})

                dyn = VelocityVerlet(
                    atoms,
                    timestep={timestep_fs} * FS,
                    logfile="md.log",
                    trajectory="md.traj",
                )
                """)

        body = (
            "# ── Molecular Dynamics ────────────────────────────────────────────────────\n"
            "import csv\n\n"
            + dyn_block
            + dedent(f"""\

                history = []

                def record():
                    step = len(history)
                    history.append({{
                        "step": step,
                        "time_fs": step * {timestep_fs},
                        "energy": atoms.get_potential_energy(),
                        "temperature_k": atoms.get_temperature(),
                    }})

                record()        # initial state (t = 0)
                dyn.attach(record, interval=1)
                dyn.run({n_steps})

                print(f"MD finished — {{len(history)}} frames recorded")

                with open("md_trajectory.csv", "w", newline="") as fh:
                    writer = csv.DictWriter(
                        fh, fieldnames=["step", "time_fs", "energy", "temperature_k"]
                    )
                    writer.writeheader()
                    writer.writerows(history)

                print("Wrote md_trajectory.csv and md.traj")
                """)
        )

    else:
        body = "# Unknown simulation mode\n"

    footer = 'print("Done.")\n'
    return header + body + "\n" + footer


# ---------------------------------------------------------------------------
# SLURM script generator
# ---------------------------------------------------------------------------


def generate_slurm(
    job_name: str = "mace_job",
    nodes: int = 1,
    ntasks: int = 1,
    cpus_per_task: int = 8,
    mem_gb: int = 32,
    time_hours: int = 24,
    partition: str = "gpu",
    use_gpu: bool = True,
    conda_env: str = "mace",
) -> str:
    """Generate a SLURM batch submission script.

    Parameters
    ----------
    job_name:
        SLURM job name (``--job-name``).
    nodes, ntasks, cpus_per_task:
        Resource allocation directives.
    mem_gb:
        Memory per node in GB.
    time_hours:
        Wall-time limit in hours.
    partition:
        SLURM partition/queue name.
    use_gpu:
        If True, add ``--gres=gpu:1``.
    conda_env:
        Conda environment to activate.

    Returns
    -------
    str
        Complete SLURM batch script as a string.
    """
    gpu_line = "#SBATCH --gres=gpu:1" if use_gpu else "# No GPU requested"
    return dedent(f"""\
        #!/bin/bash
        #SBATCH --job-name={job_name}
        #SBATCH --nodes={nodes}
        #SBATCH --ntasks={ntasks}
        #SBATCH --cpus-per-task={cpus_per_task}
        #SBATCH --mem={mem_gb}G
        #SBATCH --time={time_hours:02d}:00:00
        #SBATCH --partition={partition}
        {gpu_line}
        #SBATCH --output=slurm-%j.out
        #SBATCH --error=slurm-%j.err

        # ── Environment ─────────────────────────────────────────────────────────────
        module purge
        # Adjust the CUDA module version for your HPC system:
        module load cuda/11.8
        conda activate {conda_env}

        # ── Run ─────────────────────────────────────────────────────────────────────
        python run_mace.py

        echo "Job finished: $(date)"
        """)
